name: Fastlane Metadata Check

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Fastlane Metadata Validator
        uses: ashutoshgngwr/validate-fastlane-metadata@v2
